global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090','docker.for.mac.localhost:9090']
  - job_name: 'plain-datapipeline-job'
    scrape_interval: 5s
    static_configs:
      - targets: ['docker.for.mac.localhost:9250','docker.for.mac.localhost:9251','localhost:9250', 'localhost:9251']
  - job_name: 'keyed-window-datapipeline-job'
    scrape_interval: 5s
    static_configs:
      - targets: ['docker.for.mac.localhost:9250','docker.for.mac.localhost:9250','localhost:9250', 'localhost:9251']