scrape_configs:
  - job_name: 'plain-datapipeline-job'
    static_configs:
      - targets: ['job-cluster:9999', 'taskmanager1:9999', 'taskmanager2:9999']
  - job_name: 'keyed-window-datapipeline-job'
    static_configs:
      - targets: ['job-cluster:9999', 'taskmanager1:9999', 'taskmanager2:9999']